#!/bin/bash

set -euo pipefail

URL="https://www.youtube.com/watch?v=HEXWRTEbj1I"
WHATIS="/usr/bin/whatis"
HOSTOS="$(uname -s)"

case "$HOSTOS" in
    Linux*) XDGOPEN="$(which xdg-open)" ;;
    Darwin*) XDGOPEN="$(which open)" ;;
esac

if [[ $# -eq 0 ]]; then
    "${WHATIS}"
elif [[ "$1" != "love" ]]; then
    "${WHATIS}" "${@}"
else
    "${XDGOPEN}" "${URL}" &> /dev/null
fi

