#!/bin/bash

set -euo pipefail

WHATIS="/usr/bin/whatis"
XDGOPEN="$(which xdg-open)"
URL="https://www.youtube.com/watch?v=HEXWRTEbj1I"

if [[ -z $XDGOPEN ]]; then
    echo "Could not find xdg-open command"
    exit 14
fi

if [[ $1 != 'love' ]]; then
    "${WHATIS}" "${@}"
else
    "${XDGOPEN}" "${URL}" > /dev/null
fi

